services:
  # Backend API service
  - type: web
    name: solaceta-api
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /docs
    
  # Frontend service
  - type: web
    name: solaceta-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NEXT_PUBLIC_API_URL
        value: https://solaceta-api.onrender.com
    autoDeploy: true
    healthCheckPath: / 